envpt:
  baseLinuxIp: 8.135.1.141
  mysqlIp: ${envpt.baseLinuxIp}
  mysqlPort: 3306
  redisIp: ${envpt.baseLinuxIp}
  redisPort: 6379
  rabbitIp: ${envpt.baseLinuxIp}
  rabbitPort: 5675
  tomcatPortPre: 2

spring:
  main:
    allow-bean-definition-overriding: true
  #解决查询时间和返回的时间不一致问题
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
