--- # sms 短信
aliyun:
  sms:
    accessKeyId: "333"
    secret: "22"
    signName: 熊猫哥后台管理系统
    templateCode: "11"

spring:
  mail:
    host: smtp.qq.com
    username: 869653722@qq.com
    password: xxx
    port: 587
