# Spring配置
spring:
  application:
    name: "hugo-admin-service"
  profiles:
    active: dev,doc,log,i18n,undertow,db,redis,es,xxljob,minio,satoken

server:
  port: 12050

--- # jackson和
spring:
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  jackson:
    # 日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      # 格式化输出
      indent_output: false
      # 忽略无法转换的对象
      fail_on_empty_beans: false
    deserialization:
      # 允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false
    default-property-inclusion: non_null

