server:
  port: ${envpt.tomcatPortPre}0156

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            # 允许携带认证信息
            # 允许跨域的源(网站域名/ip)，设置*为全部
            # 允许跨域请求里的head字段，设置*为全部
            # 允许跨域的method， 默认为GET和OPTIONS，设置*为全部
            # 跨域允许的有效期
            allow-credentials: true
            allowed-origins: "*"
            allowed-headers: "*"
            allowed-methods:
              - OPTIONS
              - GET
              - POST
              - PUT
              - DELETE
            #max-age: 3600
      routes:
        - id: ty-auth
          uri: lb://ty-auth
          predicates:
            - Path=/api/ty-auth/**
          filters:
            - StripPrefix=2

        - id: ty-email
          uri: lb://ty-email
          predicates:
            - Path=/api/ty-email/**
          filters:
            - StripPrefix=2

        - id: ty-example
          uri: lb://ty-example
          predicates:
            - Path=/api/ty-example/**
          filters:
            - StripPrefix=2

            #请求数限流 名字不能随便写 ，使用默认的facatory
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 2

            # hystrix 熔断配置
            - RemoveRequestHeader=Origin #  去除请求头的origin字段，此字段导致post请求 无法进入网关post熔断
            - name: SpecialHystrix #自定义熔断
              args:
                id: SpecialHystrix
                fallbackUri: forward:/fallback
                timeout:
                  #指定接口超时处理 hystrixRibbon -> @RequestMapping("hystrixRibbon")
                  #timeoutTest-> @GetMapping("timeoutTest")  ,   -  >  /
                  hystrixRibbon-timeoutTest: 11000
                  upload-image: 2000
                  upload-file: 30000

        - id: integration-front
          uri: lb://integration-front
          predicates:
            - Path=/api/integration-front/**
          filters:
            - StripPrefix=2

        - id: ty-upload
          uri: lb://ty-upload
          predicates:
            - Path=/api/ty-upload/**
          filters:
            - StripPrefix=2

management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true


#白名单过滤
filter:
  #not filter , you can config it when dev
  #allowPaths: /
  allowPaths: swagger,docs,userRegister,userLogin,sendEmailCode,registry,login,loginOut,insertUser,export,excel,example

#默认3天时间告知前端刷新token
token-properties:
  renewTokenMinute: 1440*3


#config the visit service of  gateway  swagger
swagger-doc:
  serviceMap: {
    integration-front: "前端数据整合",
    ty-example: "使用例子"
  }