server:
  port: ${envpt.tomcatPortPre}0156
spring:
  cloud:
    gateway:
      #      globalcors:
      #        corsConfigurations:
      #          '[/**]':
      #            allow-credentials: true
      #            allowed-origin-patterns: "*"
      #            allowed-headers: "*"
      #            allowed-methods:
      #              - OPTIONS
      #              - GET
      #              - POST
      #              - PUT
      #              - DELETE
      #            #max-age: 3600
      routes:
        - id: integration-front
          uri: lb://integration-front
          metadata:
            name: "集成前端服务"
          predicates:
            - Path=/micro-service-api/integration-front/**
          filters:
            - StripPrefix=2
        - id: basis-func
          uri: lb://basis-func
          metadata:
            name: "基础功能服务"
          predicates:
            - Path=/micro-service-api/basis-func/**
          filters:
            - StripPrefix=2
management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true


#白名单过滤
filter:
  afterNeedFilterPaths: user
  allowPaths: swagger,docs,userRegister,userLogin,sendEmailCode,registry,login,loginOut,insertUser,export,excel,file,zip

#默认3天时间告知前端刷新token
token-properties:
  renewTokenMinute: 3440






