--- # 数据源配置
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    # 动态数据源文档 https://www.kancloud.cn/tracy5546/dynamic-datasource/content
    dynamic:
      # 性能分析插件(有性能损耗 不建议生产环境使用)
      p6spy: true
      # 设置默认的数据源或者数据源组,默认值即为 master
      primary: master
      # 严格模式 匹配不到数据源则报错
      strict: true
      datasource:
        # 主库数据源
        master:
          type: ${spring.datasource.type}
          driverClassName: com.mysql.cj.jdbc.Driver
          # jdbc 所有参数配置参考 https://lionli.blog.csdn.net/article/details/122018562
          # rewriteBatchedStatements=true 批处理优化 大幅提升批量插入更新删除性能(对数据库有性能损耗 使用批量操作应考虑性能问题)
          url: jdbc:mysql://111.230.198.245:3310/micro-service-single?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true&rewriteBatchedStatements=true
          username: root
          password: '@Root123'
        # 从库数据源
        #  slave:
        #    lazy: true
        #    type: ${spring.datasource.type}
        #    driverClassName: com.mysql.cj.jdbc.Driver
        #    url: jdbc:mysql://111.230.198.245:3310/ry-vue?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true&rewriteBatchedStatements=true
        #    username:
        #    password:
      hikari:
        # 最大连接池数量
        maxPoolSize: 2
        # 最小空闲线程数量
        minIdle: 1
        # 配置获取连接等待超时的时间
        connectionTimeout: 10000
        # 校验超时时间
        validationTimeout: 5000
        # 空闲连接存活最大时间，默认10分钟
        idleTimeout: 60000
        # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
        maxLifetime: 900000
        # 连接测试query（配置检测连接是否有效）
        connectionTestQuery: SELECT 1

--- # redis 单机配置(单机与集群只能开启一个另一个需要注释掉)
spring:
  redis:
    host: 111.230.198.245
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 2
    # 密码(如没有密码请注释掉)
    password: admin
    # 是否开启ssl
    ssl: false

redisson:
  # redis key前缀
  keyPrefix: hugo
  # 线程池数量
  threads: 1
  # Netty线程池数量
  nettyThreads: 2
  # 单节点配置
  singleServerConfig:
    # 客户端名称
    clientName: ${hugo.name}
    # 最小空闲连接数
    connectionMinimumIdleSize: 2
    # 连接池大小
    connectionPoolSize: 4
    # 连接空闲超时，单位：毫秒
    idleConnectionTimeout: 10000
    # 命令等待超时，单位：毫秒
    timeout: 3000
    # 发布和订阅连接池大小
    subscriptionConnectionPoolSize: 4

#是否开启跨域配置
cors:
  enabled: false

#是否开启权限拦截
satoken:
  enabled: true

#minio配置
minio:
  server-url: 111.230.198.245
  host: http://${minio.server-url}:9000
  bucket: public
  url: ${minio.host}/${minio.bucket}/
  access-key: admin
  secret-key: admin123456