#msg config，  place change to you sms config
kuanghua:
  sms:
    accessKeyId: LTAI4FrD2voTK2wTgRCPwT6d
    accessKeySecret: Zj07thnb2jiBkl4wtqgvPeuSzkJRJ3
    signName: 品优商城 # 签名名称
    verifyCodeTemplate: SMS_189216068 # 模板名称



#email config, place change to you email
spring:
  mail:
    username: 869653722@qq.com
    password: xbthzedhnxatbcab
    host: smtp.qq.com
    properties:
      mail.smtp.starttls.enable: true



server:
  port: ${envpt.tomcatPortPre}0121


#seata
seata:
  enabled: true
  enable-auto-data-source-proxy: false
  application-id: product-server
  #需要和nacos中配置保持一致config.txt service.vgroupMapping.product-server-group=default
  tx-service-group: product-server-group
  config:
    type: nacos
    nacos:
      #需要和server在同一个注册中心下
      serverAddr: 8.135.1.141:8848
      #需要server端(registry和config)、nacos配置client端(registry和config)保持一致
      group: SEATA_GROUP
      userName: "jzfai"
      password: "123456"
  registry:
    type: nacos
    nacos:
      #需要和server端保持一致，即server在nacos中的名称，默认为seata-server
      application: seata-server
      server-addr: 8.135.1.141:8848
      #需要server端(registry和config)、nacos配置client端(registry和config)保持一致
      group: SEATA_GROUP
      userName: "jzfai"


#canal配置
canal:
  client:
    instances:
      example:
        host: 8.135.1.141
        port: 11111
